---
# tasks file for cloc - Debian/Ubuntu Family

- name: Debian/Ubuntu Family | Installing {{ cloc_app }}
  apt:
    name: "{{ cloc_app }}"
    state: "{{ cloc_desired_state }}"
    force_apt_get: yes
    update_cache: yes
